services:
  spring-api:
    image: openjdk:22-jdk
    container_name: reward-receipt-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_APPLICATION_NAME: reward-receipt
      SERVER_PORT: 8080
    command: ["java", "-jar", "/ReceiptRewards-0.0.1-SNAPSHOT.jar"]
    restart: on-failure
